# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iabs_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descreva o t\xedtulo/Objetivo da possibilidade')),
                ('apoiador', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Institui\xe7\xe3o financiadora ou poss\xedvel apoiador')),
                ('chave', models.CharField(blank=True, max_length=15, null=True)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor em R$', max_digits=15, null=True, verbose_name='Valor estimado da possibilidade')),
                ('periodo_execucao', models.IntegerField(blank=True, null=True, verbose_name='Informe o per\xedodo em meses.')),
                ('prazo_limite', models.DateField(default=datetime.date.today, verbose_name='Data da publica\xe7\xe3o')),
                ('tema_possibilidade', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descreva o tema da possibilidade')),
                ('descricao_possibilidade', models.TextField(help_text='Inserir equivalente a 10 linhas', max_length=5000, verbose_name='Descri\xe7\xe3o resumida da possibilidade')),
                ('localizacao_mundial', models.IntegerField(choices=[(0, 'Nacional'), (1, 'Internacional'), (2, 'Regional'), (3, 'Estadual'), (4, 'Municipal')], default=0, null=True, verbose_name='Localiza\xe7\xe3o da possibilidade')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iabs_main.Geral_Status')),
            ],
        ),
    ]
