# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrangencia_Atuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('texto', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\xc1rea de atua\xe7\xe3o do projeto')),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descri\xe7\xe3o da \xe1rea de atua\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('texto', models.CharField(blank=True, max_length=1000, null=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario_Perfil')),
            ],
        ),
    ]
