# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-08 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('iabs_main', '0001_initial'),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descreva o t\xedtulo/Objetivo')),
                ('apoiador', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Institui\xe7\xe3o financiadora ou poss\xedvel apoiador')),
                ('chave', models.CharField(blank=True, max_length=15, null=True)),
                ('valor_estimado', models.CharField(blank=True, help_text='Valor em R$', max_length=1000, null=True, verbose_name='Valor estimado')),
                ('tema_possibilidade', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descreva o tema')),
                ('prazo_limite', models.DateField(blank=True, default=datetime.date.today, verbose_name='Data da publica\xe7\xe3o')),
                ('descricao', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Descri\xe7\xe3o resumida')),
                ('periodo_execucao', models.IntegerField(blank=True, null=True, verbose_name='Informe o per\xedodo em meses.')),
                ('check_possibilidade_cadastro_basico', models.NullBooleanField(default=False)),
                ('check_possibilidade_cadastro_financeiro', models.NullBooleanField(default=False)),
                ('check_possibilidade_cadastro_nucleo', models.NullBooleanField(default=False)),
                ('check_possibilidade_cadastro_localizacao', models.NullBooleanField(default=False)),
                ('localizacao_mundial', models.IntegerField(choices=[(0, 'Nacional'), (1, 'Internacional'), (2, 'Regional'), (3, 'Estadual'), (4, 'Municipal')], default=0, verbose_name='Localiza\xe7\xe3o da possibilidade')),
                ('localizacao_descricao', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Outras informa\xe7\xf5es em rela\xe7\xe3o a localiza\xe7\xe3o')),
                ('localizacao_abrangencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Abrangencia_Atuacao')),
                ('possibilidade_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario_Perfil')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iabs_main.Geral_Status')),
            ],
        ),
    ]
