# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='valor_estimado',
            field=models.CharField(blank=True, help_text='Valor em R$', max_length=1000, null=True, verbose_name='Valor estimado da possibilidade'),
        ),
    ]
