# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('projeto', '0003_historico_projeto_nucleo_x_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao_Possibilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('adequacao', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Descri\xe7\xe3o resumida')),
                ('categoria', models.IntegerField(choices=[(0, 'Informa\xe7\xf5es B\xe1sicas'), (1, 'Informa\xe7oes Finaceiras'), (2, 'N\xfacleos'), (3, 'Area de Atua\xe7\xe3o')], default=0, verbose_name='Categoria da adequa\xe7\xe3o')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto')),
                ('user_avaliador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario_Perfil')),
            ],
        ),
    ]
