# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('projeto', '0004_auto_20180504_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('texto', models.CharField(blank=True, max_length=1000, null=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario_Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Nucleo_Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Nucleo')),
            ],
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='descricao_possibilidade',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='modified_user',
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Descri\xe7\xe3o resumida'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tema_possibilidade',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descreva o tema'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descreva o t\xedtulo/Objetivo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='valor_estimado',
            field=models.CharField(blank=True, help_text='Valor em R$', max_length=1000, null=True, verbose_name='Valor estimado'),
        ),
        migrations.AddField(
            model_name='nucleo_projeto',
            name='fk_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='fk_nucleo',
            field=models.ManyToManyField(blank=True, through='projeto.Nucleo_Projeto', to='projeto.Nucleo', verbose_name='Nucleos do projeto'),
        ),
    ]
