# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_avaliacao_possibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao_possibilidade',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
    ]
