# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_auto_20180726_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao_possibilidade',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
        migrations.AlterField(
            model_name='avaliacao_possibilidade',
            name='user_avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario_Perfil'),
        ),
    ]
