# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0006_projeto_check_possibilidade_cadastro_basico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='iabs_main.Geral_Status'),
        ),
    ]
