# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-27 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0007_auto_20180726_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='check_projeto_potencial_cadastro_basico',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projeto',
            name='check_projeto_potencial_cadastro_financeiro',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projeto',
            name='check_projeto_potencial_cadastro_localizacao',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projeto',
            name='check_projeto_potencial_cadastro_nucleo',
            field=models.NullBooleanField(default=False),
        ),
    ]
