# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0007_auto_20180514_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='check_possibilidade_cadastro',
            new_name='check_possibilidade_cadastro_financeiro',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='check_possibilidade_local',
            new_name='check_possibilidade_cadastro_financiador',
        ),
        migrations.AddField(
            model_name='projeto',
            name='check_possibilidade_cadastro_localizacao',
            field=models.NullBooleanField(default=False),
        ),
    ]
