# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 05:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0008_auto_20180514_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='prazo_limite',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Data da publica\xe7\xe3o'),
        ),
    ]
