# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0011_auto_20180928_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento_x_projeto',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='documento_x_projeto',
            name='projeto',
        ),
        migrations.AddField(
            model_name='documento',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
        migrations.DeleteModel(
            name='Documento_x_Projeto',
        ),
    ]
