# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-01 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_notificacao_usuario_modified_user'),
        ('projeto', '0012_auto_20181001_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe_Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario_Perfil')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto')),
            ],
        ),
    ]
