# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-02 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0013_equipe_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe_projeto',
            name='responsabilidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
