# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-02 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0015_equipe_projeto_responsabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='info_contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='justificativa_prioridade',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Justificativa da Prioridade'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='prioridade_projeto',
            field=models.IntegerField(choices=[(0, 'Alta'), (1, 'M\xe9dia'), (2, 'Baixa')], default=0, verbose_name='Prioridade do Projeto'),
        ),
    ]
