# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-02 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_notificacao_usuario_modified_user'),
        ('projeto', '0016_auto_20181002_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Instrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario_Perfil')),
            ],
        ),
        migrations.AddField(
            model_name='parceiro',
            name='existe_instrumento_formal',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'N\xe3o')], default='NAO', max_length=50, null=True, verbose_name='J\xe1 existe algum instrumento formal ?'),
        ),
        migrations.AddField(
            model_name='parceiro',
            name='formaliza_parceria',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'N\xe3o')], default='NAO', max_length=50, null=True, verbose_name='\xc9 necess\xe1rio formaliza\xe7\xe3o de parceria ?'),
        ),
        migrations.AddField(
            model_name='parceiro',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
