# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-02 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0017_auto_20181002_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='tipo_instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Tipo_Instrumento', verbose_name='Tipo de instrumento espec\xedfico.'),
        ),
    ]
