# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-03 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0020_auto_20181003_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='parceiro',
            name='homepage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='justificativa_padrao',
            field=models.IntegerField(choices=[(1, 'M\xe9dia'), (2, 'Baixa'), (3, 'Baixa'), (4, 'Baixa')], default=0, verbose_name='Justificativa padr\xe3o do Projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='origem_projeto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='protocolo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='titulo_abreviado',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descreva o t\xedtulo/Objetivo abreviado'),
        ),
        migrations.AlterField(
            model_name='equipe_projeto',
            name='responsabilidade',
            field=models.IntegerField(blank=True, choices=[(0, 'Administrativo'), (1, 'Financeiro'), (2, 'T\xe9cnico'), (3, 'Institucional')], default=0, verbose_name='Categoria da responsavili'),
        ),
    ]
