# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-04 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iabs_main', '0002_auto_20181003_2037'),
        ('projeto', '0022_auto_20181004_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_x_Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('estado_projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iabs_main.Estado')),
            ],
        ),
        migrations.AlterField(
            model_name='projeto',
            name='localizacao_abrangencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Abrangencia_Atuacao'),
        ),
        migrations.AddField(
            model_name='estado_x_projeto',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
    ]
