# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-04 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iabs_main', '0003_pais'),
        ('projeto', '0023_auto_20181004_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio_x_Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('municipio_projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iabs_main.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Regiao_x_Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='localizacao_abrangencia',
        ),
        migrations.DeleteModel(
            name='Abrangencia_Atuacao',
        ),
        migrations.AddField(
            model_name='regiao_x_projeto',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
        migrations.AddField(
            model_name='regiao_x_projeto',
            name='regiao_projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iabs_main.Regiao'),
        ),
        migrations.AddField(
            model_name='municipio_x_projeto',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
    ]
