# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iabs_main', '0003_pais'),
        ('projeto', '0024_auto_20181004_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais_x_Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pais_projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iabs_main.Pais')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto')),
            ],
        ),
    ]
