# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0025_pais_x_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_gasto', models.DateTimeField()),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('valor', models.CharField(blank=True, help_text='Valor em R$', max_length=100, null=True, verbose_name='Valor estimado')),
                ('fase_gasto', models.CharField(max_length=50, null=True, verbose_name='Fase do projeto')),
            ],
        ),
        migrations.AlterField(
            model_name='projeto',
            name='justificativa_padrao',
            field=models.IntegerField(choices=[(1, 'Justificativa 01'), (2, 'Justificativa 02'), (3, 'Justificativa 03'), (4, 'Justificativa 04')], default=0, verbose_name='Justificativa padr\xe3o do Projeto'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
    ]
