# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0026_auto_20181004_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro_x_Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='parceiro',
            name='projeto',
        ),
        migrations.AddField(
            model_name='parceiro_x_projeto',
            name='parceiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Parceiro'),
        ),
        migrations.AddField(
            model_name='parceiro_x_projeto',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
    ]
