# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-05 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0026_auto_20181004_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='num_protocolo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
