# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0027_projeto_num_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ano_protocolo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='protocolo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
