# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-10 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0027_auto_20181008_1345'),
        ('projeto', '0028_auto_20181009_1359'),
    ]

    operations = [
    ]
