INSERT INTO iabs_main_regiao (id, nome) VALUES (1, 'Norte');
INSERT INTO iabs_main_regiao (id, nome) VALUES (2, 'Nordeste');
INSERT INTO iabs_main_regiao (id, nome) VALUES (3, 'Sudeste');
INSERT INTO iabs_main_regiao (id, nome) VALUES (4, 'Sul');
INSERT INTO iabs_main_regiao (id, nome) VALUES (5, 'Centro-Oeste');


INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (12, 12, 'Acre', 'AC', 1);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (27, 27, 'Alagoas', 'AL', 2);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (16, 16, 'Amapá', 'AP', 1);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (13, 13, 'Amazonas', 'AM', 1);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (29, 29, 'Bahia', 'BA', 2);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (23, 23, 'Ceará', 'CE', 2);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (53, 53, 'Distrito Federal', 'DF', 5);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (32, 32, 'Espírito Santo', 'ES', 3);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (52, 52, 'Goiás', 'GO', 5);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (21, 21, 'Maranhão', 'MA', 2);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (51, 51, 'Mato Grosso', 'MT', 5);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (50, 50, 'Mato Grosso do Sul', 'MS', 5);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (31, 31, 'Minas Gerais', 'MG', 3);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (15, 15, 'Pará', 'PA', 1);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (25, 25, 'Paraíba', 'PB', 2);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (41, 41, 'Paraná', 'PR', 4);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (26, 26, 'Pernambuco', 'PE', 2);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (22, 22, 'Piauí', 'PI', 2);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (33, 33, 'Rio de Janeiro', 'RJ', 3);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (24, 24, 'Rio Grande do Norte', 'RN', 2);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (43, 43, 'Rio Grande do Sul', 'RS', 4);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (11, 11, 'Rondônia', 'RO', 1);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (14, 14, 'Roraima', 'RR', 1);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (42, 42, 'Santa Catarina', 'SC', 4);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (35, 35, 'São Paulo', 'SP', 3);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (28, 28, 'Sergipe', 'SE', 2);
INSERT INTO iabs_main_estado (id, codigo_uf, nome, uf, regiao_id) values (17, 17, 'Tocantins', 'TO', 1);
