# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do usuario')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('idade', models.IntegerField(blank=True, default=0, null=True, verbose_name='Idade')),
                ('sexo', models.IntegerField(blank=True, choices=[(0, 'Feminino'), (1, 'Masculino')], default=0, null=True, verbose_name='Genero')),
            ],
        ),
    ]
