# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-15 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo')),
                ('descricao', models.CharField(max_length=14, unique=True, verbose_name='Descricao')),
                ('tipo', models.CharField(max_length=14, unique=True, verbose_name='Tipo')),
                ('visualizada', models.BooleanField(default=False, verbose_name='Recomposi\xe7\xe3o da Mata Ciliar')),
                ('referencia', models.IntegerField(blank=True, null=True, verbose_name='Projeto id')),
            ],
        ),
    ]
