# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-27 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_perfil_user_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao_usuario',
            name='descricao',
            field=models.CharField(max_length=500, unique=True, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='notificacao_usuario',
            name='tipo',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tipo'),
        ),
    ]
