# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-27 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20180927_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao_usuario',
            name='descricao',
            field=models.CharField(max_length=500, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='notificacao_usuario',
            name='tipo',
            field=models.CharField(max_length=200, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacao_usuario',
            name='visualizada',
            field=models.BooleanField(default=False),
        ),
    ]
