# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iabs_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geral_status',
            name='next_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geral_status',
            name='previous_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geral_status',
            name='cod_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
