# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-04 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iabs_main', '0002_auto_20181003_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_pt', models.CharField(blank=True, max_length=150, null=True)),
                ('iso2', models.CharField(blank=True, max_length=150, null=True)),
                ('iso3', models.CharField(blank=True, max_length=150, null=True)),
                ('bacen', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
